"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimeNavBar } from "@/components/ui/anime-navbar";
import { ScrollProgress } from "@/components/ui/scroll-progress";
import { Home, FileText, CreditCard, User } from "lucide-react";

const chassiTest = localFont({
  src: [
    {
      path: "../fonts/Chassi_Test/ChassiTestL-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Chassi_Test/ChassiTestL-Medium.otf",
      weight: "500", 
      style: "normal",
    },
    {
      path: "../fonts/Chassi_Test/ChassiTestL-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Chassi_Test/ChassiTestL-Italic.otf",
      weight: "400",
      style: "italic",
    }
  ],
  variable: "--font-chassi-test",
  display: "swap",
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navItems = [
  {
    name: "Home",
    url: "#hero-section",
    href: "#hero-section",
    icon: Home,
  },
  {
    name: "About",
    url: "#about-section",
    href: "#about-section",
    icon: User,
  },
  {
    name: "Showcase",
    url: "#product-showcase",
    href: "#product-showcase",
    icon: FileText,
  },
  {
    name: "Contact",
    url: "#cta-section",
    href: "#cta-section",
    icon: CreditCard,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chassiTest.variable} ${inter.variable} antialiased`}
      >
        <ScrollProgress />
        <AnimeNavBar items={navItems} defaultActive="Home" />
        {children}
      </body>
    </html>
  );
}
